### ISSUE TITLE
[bug] Double click is not brining up menu on v10(build 291) dnd 2.1.4 world

### ISSUE THREAD

**Issue by mcabel** [teroparvinen/foundry-scene-helpers#1]
Single click is working properly but double click is not opening the settings menu. 

The setting was configured and active. Upon checking f12, no changes happen when double clicking a scene(but single click work as intended, opening the scene).

**Comment by teroparvinen** [comment]
The double click only works from the scene navigation bar, i.e. the strip of scene names on top of the scene. Double clicking in the side bar doesn't do anything. Unfortunately, there is no easy way to get this to happen in the side bar due to technical issues, but you can already alt-click there to open the settings for any scene listed.

Can you confirm that this was your issue or is there still some bug at play?

**Comment by mcabel** [comment]
![image](https://github.com/teroparvinen/foundry-scene-helpers/assets/10392829/3f764c14-095a-4f25-91a0-010cb85401f7)

mmm yeah it is still an issue with no mods aside from this enabled. But also comes from my own expectations and I did not know that they "side bar" and "navigation bar" cannot behave the same way due technical issues. Thanks for checking it out.
